# Generated by Django 4.2 on 2023-04-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catégorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomC', models.CharField(choices=[('Aviation', 'Aviation'), ('Marine', 'Marine')], max_length=50, verbose_name='Catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP_mr', models.CharField(max_length=50, verbose_name='Produit')),
                ('prix_mr', models.IntegerField(default=0, verbose_name='Prix par Litre')),
                ('description_mr', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='description')),
                ('image_mr', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('catégorie_mr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produit.catégorie', verbose_name='catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomP', models.CharField(max_length=50, verbose_name='Produit')),
                ('prix', models.IntegerField(default=0, verbose_name='Prix par Litre')),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('catégorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produit.catégorie')),
            ],
        ),
    ]
