# Generated by Django 4.1.7 on 2023-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_AV', models.CharField(max_length=50, verbose_name='Produit')),
                ('prix_promoAV', models.FloatField(default=0, verbose_name='Prix Promo')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_MR', models.CharField(max_length=50, verbose_name='Produit')),
                ('prix_promoMR', models.FloatField(default=0, verbose_name='Prix Promo')),
            ],
        ),
        migrations.AlterField(
            model_name='produitav',
            name='prix',
            field=models.FloatField(default=0, verbose_name='Prix par Litre'),
        ),
        migrations.AlterField(
            model_name='produitmr',
            name='prix_mr',
            field=models.FloatField(default=0, verbose_name='Prix par Litre'),
        ),
    ]
