# Generated by Django 4.1.7 on 2023-04-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0003_alter_promotionav_p_av_alter_promotionmr_p_mr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionav',
            name='P_AV',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produit.produitav', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='promotionmr',
            name='P_MR',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produit.produitmr', verbose_name='Produit'),
        ),
    ]
