# Generated by Django 4.1.7 on 2023-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0005_produitav_prp_av_produitmr_prp_mr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionmr',
            name='P_MR',
        ),
        migrations.AlterField(
            model_name='produitav',
            name='prP_av',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produitmr',
            name='prP_mr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='PromotionAV',
        ),
        migrations.DeleteModel(
            name='PromotionMR',
        ),
    ]
