# Generated by Django 4.1.7 on 2023-04-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0006_remove_promotionmr_p_mr_alter_produitav_prp_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitav',
            name='prP_av',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='produitmr',
            name='prP_mr',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
