# Generated by Django 4.1.7 on 2023-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0007_alter_produitav_prp_av_alter_produitmr_prp_mr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitav',
            name='prP_av',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Promotion'),
        ),
        migrations.AlterField(
            model_name='produitmr',
            name='prP_mr',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Promotion'),
        ),
    ]
