# Generated by Django 4.1.7 on 2023-04-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0008_alter_produitav_prp_av_alter_produitmr_prp_mr'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitav',
            name='prixD',
            field=models.FloatField(default=0, verbose_name='Prix (Dollar)'),
        ),
        migrations.AddField(
            model_name='produitmr',
            name='prix_mrD',
            field=models.FloatField(default=0, verbose_name='Prix (Dollar)'),
        ),
        migrations.AlterField(
            model_name='produitav',
            name='prix',
            field=models.FloatField(default=0, verbose_name='Prix (Dinar)'),
        ),
        migrations.AlterField(
            model_name='produitmr',
            name='prix_mr',
            field=models.FloatField(default=0, verbose_name='Prix (Dinar)'),
        ),
    ]
