# Generated by Django 4.2 on 2023-04-19 17:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nameAV', models.CharField(max_length=50, verbose_name="nom d'utilisateur")),
                ('type_client', models.CharField(choices=[('Aviation', 'Aviation'), ('Marine', 'Marine')], max_length=30, null=True)),
                ('phone', models.CharField(max_length=10, verbose_name='num telephone')),
                ('email', models.EmailField(max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLiv_AV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_SiteAV', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLiv_MR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_SiteMR', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandeMr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitymr', models.IntegerField(verbose_name='quantité')),
                ('pricemr', models.IntegerField(verbose_name='prix total')),
                ('dateC', models.DateField(default=datetime.datetime.today)),
                ('Confirmer_Commande_mr', models.BooleanField(default=False, verbose_name='Confirmer Commande')),
                ('Annuler_Commande_mr', models.BooleanField(default=False, verbose_name='Annuler Commande')),
                ('etat_payementmr', models.BooleanField(blank=True, default=False, verbose_name='etat payement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Aviation.clientav')),
                ('produitmr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produit.produitmr', verbose_name='produit')),
                ('site_Livraison_Marine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Aviation.siteliv_mr')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeAv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantité')),
                ('price', models.IntegerField(verbose_name='prix total')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('Confirmer_Commande', models.BooleanField(default=False)),
                ('Annuler_Commande', models.BooleanField(default=False)),
                ('etat_payementav', models.BooleanField(blank=True, default=False, verbose_name='etat payement')),
                ('clientAV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Aviation.clientav', verbose_name='client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produit.produitav')),
                ('site_Livraison_Aviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Aviation.siteliv_av')),
            ],
        ),
    ]
