# Generated by Django 4.2 on 2023-04-20 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeav',
            name='date_Livraison_av',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commandemr',
            name='date_Livraison_mr',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='commandeav',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name="date d'envoi de la commande"),
        ),
        migrations.AlterField(
            model_name='commandemr',
            name='dateC',
            field=models.DateField(default=datetime.datetime.today, verbose_name="date d'envoi de la commande"),
        ),
    ]
