# Generated by Django 4.2 on 2023-04-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0002_commandeav_date_livraison_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeav',
            name='date_Livraison_av',
            field=models.DateField(blank=True, null=True, verbose_name='date livrason'),
        ),
        migrations.AlterField(
            model_name='commandemr',
            name='date_Livraison_mr',
            field=models.DateField(blank=True, null=True, verbose_name='date livraison'),
        ),
    ]
