# Generated by Django 4.1.7 on 2023-04-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0003_alter_commandeav_date_livraison_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeav',
            name='price',
            field=models.FloatField(verbose_name='prix total'),
        ),
        migrations.AlterField(
            model_name='commandemr',
            name='pricemr',
            field=models.FloatField(verbose_name='prix total'),
        ),
    ]
