# Generated by Django 4.1.7 on 2023-04-24 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0004_alter_commandeav_price_alter_commandemr_pricemr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeav',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='date recu commande'),
        ),
        migrations.AlterField(
            model_name='commandemr',
            name='dateC',
            field=models.DateField(default=datetime.datetime.today, verbose_name='date recu commande'),
        ),
    ]
