# Generated by Django 4.1.7 on 2023-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0005_alter_commandeav_date_alter_commandemr_datec'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeav',
            name='type_deviseAv',
            field=models.CharField(choices=[('DA', 'DA'), ('$', '$')], max_length=10, null=True, verbose_name='type devise'),
        ),
        migrations.AddField(
            model_name='commandemr',
            name='type_deviseMr',
            field=models.CharField(choices=[('DA', 'DA'), ('$', '$')], max_length=10, null=True, verbose_name='type devise'),
        ),
    ]
