# Generated by Django 4.1.7 on 2023-04-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0006_commandeav_type_deviseav_commandemr_type_devisemr'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientav',
            name='pays',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
