# Generated by Django 4.1.7 on 2023-04-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0007_clientav_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientav',
            name='avatar',
            field=models.ImageField(blank=True, default='kisspng-logo-person-user-person-icon-5b4d2bd1eadf26.611780081531784145962.jpg', null=True, upload_to=''),
        ),
    ]
