# Generated by Django 4.1.7 on 2023-05-04 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0008_alter_clientav_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandeav',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='clientav',
            name='avatar',
            field=models.ImageField(blank=True, default='images/img/kisspng-logo-person-user-person-icon-5b4d2bd1eadf26.611780081531784145962.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='commandeav',
            name='date_Livraison_av',
            field=models.DateField(blank=True, help_text='Please enter the date in <em>YYYY-MM-DD</em> format.', null=True, verbose_name='date livrason'),
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailCl', models.EmailField(max_length=50, verbose_name='Email Client')),
                ('sujet', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1500)),
                ('dateRec', models.DateField(default=datetime.datetime.today, verbose_name='date recu reclamation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Aviation.clientav', verbose_name='Nom Client')),
            ],
        ),
    ]
