# Generated by Django 4.1.7 on 2023-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0010_rename_client_reclamation_clientrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='clientRc',
            field=models.CharField(max_length=30, verbose_name='Nom Client'),
        ),
    ]
