# Generated by Django 4.1.7 on 2023-05-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Aviation', '0011_alter_reclamation_clientrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientav',
            name='CodeClient',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
